### ISSUE TITLE
CI/CD Error in Step 5 Building the sample_pipeline

### ISSUE THREAD

**Issue by rdrichar** [ibm-cloud-architecture/refarch-cloudnative-devops-kubernetes#7]
I am trying the "Create and Run a Sample CI/CD Pipeline" path.  I am on ICp 2.1.0.1 and I have installed Jenkins 2.67 per these instructions.  All looks OK.  At Step 5/6 though, when I try to build my pipeline, I get the following error.  

Started by user admin
Obtained Jenkinsfile from git https://github.com/ibm-cloud-architecture/refarch-cloudnative-bluecompute-web
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node

Still waiting to schedule task
jenkins-slave-5xldx-tbf2t is offline

Running on jenkins-slave-5xldx-tbf2t in /home/jenkins/workspace/sample_pipeline
[Pipeline] {
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: scm for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:242)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:284)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:288)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:264)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:264)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.run(WorkflowScript:13)
	at ___cps.transform___(Native Method)

Any Ideas as to what's causing this problem and how I can fix it?

**Comment by rdrichar** [comment]
I found a fix here:  https://issues.jenkins-ci.org/browse/JENKINS-33629.   The fix required me to install the Pipeline: Job plug-in for Jenkins.  This turned out to be easy enough to do from the Jenkins plug-in manager.
